# Generated by Django 5.0.6 on 2024-05-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inovacaowebsite', '0003_contato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-data'], 'verbose_name_plural': 'Albuns'},
        ),
        migrations.AlterModelOptions(
            name='contato',
            options={'ordering': ['-data']},
        ),
        migrations.AlterModelOptions(
            name='imagem',
            options={'ordering': ['-data'], 'verbose_name_plural': 'Imagens'},
        ),
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.CharField(default='Inovação JFPB', max_length=100),
        ),
    ]
