# Generated by Django 5.0.5 on 2024-06-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inovacaowebsite', '0004_alter_album_options_alter_contato_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='descricao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
