# Generated by Django 4.2.10 on 2024-06-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inovacaowebsite', '0005_equipe_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='premios')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('conteudo', models.TextField()),
                ('autor', models.CharField(default='Inovação JFPB', max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='projetos')),
                ('titulo', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'Em andamento'), (1, 'Concluído'), (2, 'Cancelado')], default=0)),
                ('descricao', models.TextField()),
                ('conteudo', models.TextField()),
                ('autor', models.CharField(default='Inovação JFPB', max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-data'], 'verbose_name_plural': 'Albuns'},
        ),
    ]
