# Generated by Django 4.2.10 on 2024-06-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inovacaowebsite', '0006_premio_projeto_alter_noticia_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('Pendência', 'Pendência'), ('Em Andamento', 'Em Andamento'), ('Conclusão', 'Conclusão')], default='Pendência', max_length=24),
        ),
    ]
