# Generated by Django 4.2.10 on 2024-06-24 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inovacaowebsite', '0007_alter_projeto_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legislacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Legislação',
                'verbose_name_plural': 'Legislações',
            },
        ),
        migrations.CreateModel(
            name='Tipo_De_Legislacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=48, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Legislação',
                'verbose_name_plural': 'Tipos de Legislações',
            },
        ),
        migrations.CreateModel(
            name='Legislacao_Informacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('nome', models.CharField(max_length=100)),
                ('lei', models.CharField(max_length=100)),
                ('ano', models.CharField(max_length=4)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inovacaowebsite.legislacao')),
            ],
            options={
                'verbose_name': 'Legislação Informação',
                'verbose_name_plural': 'Legislação Informações',
                'ordering': ['-data'],
            },
        ),
        migrations.AddField(
            model_name='legislacao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inovacaowebsite.tipo_de_legislacao'),
        ),
    ]
